{% set name = "cmsip" %}
{% set version = "0.0.2.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "de9d1d941c9f5226c2e73b6701428adb2ccce47864a3266a2a3725f4c6375b9a"

build:
  number: 0
  entry_points:
    - cmsip=cmsip.cmsip:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python

requirements:
  host:
    - pip
    - python >=3
  run:
    - matplotlib
    - python >=3
    - pyyaml
    - bedtools
    - r-base
    - bioconductor-deseq2
    - bioconductor-genefilter
    - r-rvaidememoire
    - gawk
    - moabs

test:
  imports:
    - cmsip
  commands:
    - cmsip --help

about:
  home: "https://github.com/lijinbio/cmsip"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE"
  summary: "A package for detecting differential 5hmC regions from CMS-IP sequencing data."

extra:
  recipe-maintainers:
    - lijinbio
