{% set version = "0.3.4" %}
{% set sha256 = "1787353823e2cc9843eb29a53cd99345687bac0215b9c501f0e67bf488d845eb" %}

package:
  name: calib
  version: {{ version }}

source:
  url: https://github.com/vpc-ccg/calib/archive/v{{ version }}.zip
  sha256: {{ sha256 }}
  patches: 
    - Makefile.patch

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
  host:
    - zlib
  run:
    - zlib
test:
  commands:
    - calib --help

about:
  home: https://github.com/vpc-ccg/calib
  license: MIT
  license_file: LICENSE
  summary: Clustering without alignment using (locality sensitive hashing) LSH and MinHashing of barcoded reads
