{% set version = '1.0.1' %}

package:
  name: r-nacho
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/NACHO_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/NACHO/NACHO_{{ version }}.tar.gz
  sha256: 465f832d78af642daf8647a2526a27ae43689ac53bcd8f25afc7dd9c9d74b193

build:
  noarch: generic

  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-cli >=1.1.0
    - r-crayon >=1.3.4
    - r-dplyr >=0.8.3
    - r-ggbeeswarm >=0.6.0
    - r-ggforce >=0.3.1
    - r-ggplot2 >=3.2.1
    - r-ggrepel >=0.8.1
    - r-knitr >=1.25
    - r-magrittr >=1.5
    - r-purrr >=0.3.3
    - r-rlang >=0.1.2
    - r-rmarkdown >=1.16
    - r-rstudioapi >=0.10
    - r-scales >=1.0.0
    - r-sessioninfo >=1.1.1
    - r-shiny >=1.4.0
    - r-shinywidgets >=0.4.9
    - r-tibble >=2.1.3
    - r-tidyr >=1.0.0

  run:
    - r-base
    - r-cli >=1.1.0
    - r-crayon >=1.3.4
    - r-dplyr >=0.8.3
    - r-ggbeeswarm >=0.6.0
    - r-ggforce >=0.3.1
    - r-ggplot2 >=3.2.1
    - r-ggrepel >=0.8.1
    - r-knitr >=1.25
    - r-magrittr >=1.5
    - r-purrr >=0.3.3
    - r-rlang >=0.1.2
    - r-rmarkdown >=1.16
    - r-rstudioapi >=0.10
    - r-scales >=1.0.0
    - r-sessioninfo >=1.1.1
    - r-shiny >=1.4.0
    - r-shinywidgets >=0.4.9
    - r-tibble >=2.1.3
    - r-tidyr >=1.0.0

test:
  commands:
    - $R -e "library('NACHO')"

about:
  home: https://github.com/mcanouil/NACHO, https://mcanouil.github.io/NACHO
  license: GPL-3
  summary: NanoString nCounter data are gene expression assays where there is no need for the
    use of enzymes or amplification protocols and work with fluorescent barcodes (Geiss
    et al. (2018) <doi:10.1038/nbt1385>). Each barcode is assigned a messenger-RNA/micro-RNA
    (mRNA/miRNA) which after bonding with its target can be counted. As a result each
    count of a specific barcode represents the presence of its target mRNA/miRNA. 'NACHO'
    (NAnoString quality Control dasHbOard) is able to analyse the exported NanoString
    nCounter data and facilitates the user in performing a quality control. 'NACHO'
    does this by visualising quality control metrics, expression of control genes, principal
    components and sample specific size factors in an interactive web application.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
